import ExcelJS from "exceljs";
import jsPDF from "jspdf";
import { peso } from "../lib/format";

export type ReportValueType = "text" | "number" | "currency" | "percent" | "date" | "datetime" | "time";

export interface ReportColumn {
  key: string;
  label: string;
  type?: ReportValueType;
}

export interface ReportSection {
  title: string;
  columns: ReportColumn[];
  rows: Record<string, string | number>[];
}

export interface ReportData {
  report: string;
  title: string;
  period: string;
  generatedAt: string;
  generatedBy: string;
  business: { name: string; address: string; contactNumber: string; email: string; logoUrl?: string };
  summary: Array<{ label: string; value: string | number; type?: ReportValueType }>;
  columns: ReportColumn[];
  rows: Record<string, string | number>[];
  sections: ReportSection[];
}

function filename(report: ReportData, extension: "csv" | "xlsx" | "pdf") {
  const date = new Date(report.generatedAt).toISOString().slice(0, 10);
  const title = report.title.replace(/\s+/g, "_").replace(/[^A-Za-z0-9_-]+/g, "");
  return `${title}_${date}.${extension}`;
}

function download(blob: Blob, name: string) {
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = name;
  link.click();
  URL.revokeObjectURL(url);
}

function rawValue(value: string | number | undefined) {
  if (value === undefined || value === null) return "";
  return value;
}

function displayValue(value: string | number | undefined, type?: ReportValueType) {
  if (value === undefined || value === null || value === "") return "";
  if (type === "currency") return peso(value);
  if (type === "percent") return `${Number(value).toFixed(2)}%`;
  return String(value);
}

function drawPdfText(doc: jsPDF, value: string, x: number, y: number, maxWidth?: number) {
  const pesoIndex = value.indexOf("₱");
  if (pesoIndex < 0) {
    if (maxWidth === undefined) doc.text(value, x, y);
    else doc.text(value, x, y, { maxWidth });
    return;
  }

  // jsPDF's built-in Helvetica font cannot encode ₱, so draw it as P with two bars.
  const prefix = value.slice(0, pesoIndex);
  const amount = value.slice(pesoIndex + 1).trimStart();
  const symbolX = x + doc.getTextWidth(prefix);
  if (prefix) doc.text(prefix, x, y);
  const symbolWidth = doc.getTextWidth("P");
  doc.text("P", symbolX, y);

  const capHeight = doc.getFontSize() / 2.83464567;
  const extension = Math.max(0.15, capHeight * 0.05);
  const lineWidth = doc.getLineWidth();
  doc.setLineWidth(Math.max(0.12, capHeight * 0.045));
  doc.line(symbolX - extension, y - capHeight * 0.47, symbolX + symbolWidth + extension, y - capHeight * 0.47);
  doc.line(symbolX - extension, y - capHeight * 0.25, symbolX + symbolWidth + extension, y - capHeight * 0.25);
  doc.setLineWidth(lineWidth);

  const amountX = symbolX + symbolWidth + extension;
  const amountWidth = maxWidth === undefined ? undefined : Math.max(1, x + maxWidth - amountX);
  if (amountWidth === undefined) doc.text(amount, amountX, y);
  else doc.text(amount, amountX, y, { maxWidth: amountWidth });
}

function csvCell(value: string | number | undefined, type?: ReportValueType) {
  const cell = type === "currency" || type === "number" || type === "percent" ? rawValue(value) : displayValue(value, type);
  return `"${String(typeof cell === "string" && /^[=+@\-\t\r]/.test(cell) ? "'" + cell : cell).replace(/"/g, '""')}"`;
}

export function exportReportCsv(report: ReportData) {
  if (report.rows.length === 0 && report.summary.length === 0) throw new Error("No data is available for the selected reporting period.");
  const rows = [
    ["Report", report.title],
    ["Report Period", report.period],
    ["Generated On", new Date(report.generatedAt).toLocaleString("en-PH", { timeZone: "Asia/Manila" })],
    ["Generated By", report.generatedBy],
    [],
    ["Summary"],
    ["Metric", "Value"],
    ...report.summary.map((item) => [item.label, rawValue(item.value)]),
    [],
    report.columns.map((column) => column.label),
    ...report.rows.map((row) => report.columns.map((column) => csvCell(row[column.key], column.type)))
  ];
  const csv = rows.map((row) => row.map((cell) => typeof cell === "string" && cell.startsWith("\"") ? cell : csvCell(cell)).join(",")).join("\n");
  download(new Blob([`\uFEFF${csv}`], { type: "text/csv;charset=utf-8" }), filename(report, "csv"));
}

function applyExcelFormat(cell: ExcelJS.Cell, type?: ReportValueType) {
  if (type === "currency") cell.numFmt = '"₱" #,##0.00';
  if (type === "percent") {
    cell.value = Number(cell.value ?? 0) / 100;
    cell.numFmt = "0.00%";
  }
  if (type === "number") cell.numFmt = "#,##0";
}

function addExcelTable(worksheet: ExcelJS.Worksheet, title: string, columns: ReportColumn[], rows: Record<string, string | number>[]) {
  worksheet.addRow([]);
  worksheet.addRow([title]).font = { bold: true };
  const header = worksheet.addRow(columns.map((column) => column.label));
  header.font = { bold: true };
  header.eachCell((cell) => {
    cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFE2E8F0" } };
    cell.border = { top: { style: "thin" }, left: { style: "thin" }, bottom: { style: "thin" }, right: { style: "thin" } };
  });
  for (const row of rows) {
    const excelRow = worksheet.addRow(columns.map((column) => rawValue(row[column.key])));
    excelRow.eachCell((cell, index) => {
      applyExcelFormat(cell, columns[index - 1]?.type);
      cell.border = { top: { style: "thin" }, left: { style: "thin" }, bottom: { style: "thin" }, right: { style: "thin" } };
    });
  }
}

export async function exportReportExcel(report: ReportData) {
  if (report.rows.length === 0 && report.summary.length === 0) throw new Error("No data is available for the selected reporting period.");
  const workbook = new ExcelJS.Workbook();
  workbook.creator = "SmartStock";
  workbook.created = new Date();
  const worksheet = workbook.addWorksheet(report.title.slice(0, 31));
  worksheet.views = [{ state: "frozen", ySplit: 8 }];

  worksheet.addRow([report.business.name]).font = { bold: true, size: 16 };
  worksheet.addRow([report.title]).font = { bold: true, size: 14 };
  worksheet.addRow(["Report Period", report.period]);
  worksheet.addRow(["Generated On", new Date(report.generatedAt).toLocaleString("en-PH", { timeZone: "Asia/Manila" })]);
  worksheet.addRow(["Generated By", report.generatedBy]);
  worksheet.addRow([]);
  worksheet.addRow(["Summary"]).font = { bold: true };

  for (const item of report.summary) {
    const row = worksheet.addRow([item.label, rawValue(item.value)]);
    row.getCell(1).font = { bold: true };
    applyExcelFormat(row.getCell(2), item.type);
  }

  addExcelTable(worksheet, "Details", report.columns, report.rows);
  for (const item of report.sections) addExcelTable(worksheet, item.title, item.columns, item.rows);

  worksheet.columns.forEach((column) => {
    const values = column.values?.slice(1).map((value) => String(value ?? "")) ?? [];
    column.width = Math.min(Math.max(...values.map((value) => value.length), 12) + 2, 36);
  });

  const buffer = await workbook.xlsx.writeBuffer();
  download(new Blob([buffer], { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" }), filename(report, "xlsx"));
}

function drawTable(doc: jsPDF, columns: ReportColumn[], rows: Record<string, string | number>[], y: number, margin: number, usableWidth: number) {
  const pageHeight = doc.internal.pageSize.getHeight();
  const columnWidth = usableWidth / columns.length;

  function header() {
    doc.setFillColor(226, 232, 240);
    doc.rect(margin, y - 5, usableWidth, 8, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(7);
    columns.forEach((column, index) => doc.text(column.label, margin + index * columnWidth + 1, y, { maxWidth: columnWidth - 2 }));
    y += 7;
    doc.setFont("helvetica", "normal");
  }

  header();
  for (const row of rows) {
    if (y > pageHeight - 24) {
      doc.addPage();
      y = margin;
      header();
    }
    columns.forEach((column, index) => drawPdfText(doc, displayValue(row[column.key], column.type) || "-", margin + index * columnWidth + 1, y, columnWidth - 2));
    y += 7;
  }
  return y;
}

export function exportReportPdf(report: ReportData) {
  if (report.rows.length === 0 && report.summary.length === 0) throw new Error("No data is available for the selected reporting period.");
  const landscape = report.columns.length > 7;
  const doc = new jsPDF({ orientation: landscape ? "landscape" : "portrait", unit: "mm", format: "a4" });
  const margin = 12;
  const pageWidth = doc.internal.pageSize.getWidth();
  const usableWidth = pageWidth - margin * 2;
  let y = 14;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text(report.business.name, margin, y);
  y += 6;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  [report.business.address, report.business.contactNumber, report.business.email].filter(Boolean).forEach((line) => {
    doc.text(line, margin, y);
    y += 5;
  });
  y += 4;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.text(report.title.toUpperCase(), margin, y);
  y += 8;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text(`Report Period: ${report.period}`, margin, y);
  y += 5;
  doc.text(`Generated On: ${new Date(report.generatedAt).toLocaleString("en-PH", { timeZone: "Asia/Manila" })}`, margin, y);
  y += 5;
  doc.text(`Generated By: ${report.generatedBy}`, margin, y);
  y += 8;

  doc.setFont("helvetica", "bold");
  doc.text("EXECUTIVE SUMMARY", margin, y);
  y += 6;
  doc.setFont("helvetica", "normal");
  const half = usableWidth / 2;
  report.summary.forEach((item, index) => {
    const x = margin + (index % 2) * half;
    if (index > 0 && index % 2 === 0) y += 5;
    drawPdfText(doc, `${item.label}: ${displayValue(item.value, item.type)}`, x, y, half - 4);
  });
  y += 10;

  doc.setFont("helvetica", "bold");
  doc.text("DETAILS", margin, y);
  y += 7;
  doc.setFont("helvetica", "normal");
  y = drawTable(doc, report.columns, report.rows, y, margin, usableWidth);

  for (const pageNumber of Array.from({ length: doc.getNumberOfPages() }, (_, index) => index + 1)) {
    doc.setPage(pageNumber);
    doc.setFontSize(8);
    doc.text(`Page ${pageNumber} of ${doc.getNumberOfPages()}`, pageWidth - margin, doc.internal.pageSize.getHeight() - 8, { align: "right" });
    doc.text("System Generated Report", margin, doc.internal.pageSize.getHeight() - 8);
  }

  doc.save(filename(report, "pdf"));
}
