import ExcelJS from "exceljs";
import jsPDF from "jspdf";
import { peso } from "../lib/format";

export type ReportValueType = "text" | "number" | "currency" | "percent" | "date" | "datetime" | "time";

export interface ReportColumn {
  key: string;
  label: string;
  type?: ReportValueType;
}

export interface ReportSection {
  title: string;
  columns: ReportColumn[];
  rows: Record<string, string | number>[];
}

export interface ReportData {
  report: string;
  title: string;
  period: string;
  generatedAt: string;
  generatedBy: string;
  business: { name: string; address: string; contactNumber: string; email: string; logoUrl?: string };
  summary: Array<{ label: string; value: string | number; type?: ReportValueType }>;
  columns: ReportColumn[];
  rows: Record<string, string | number>[];
  sections: ReportSection[];
}

function filename(report: ReportData, extension: "csv" | "xlsx" | "pdf") {
  const date = new Date(report.generatedAt).toISOString().slice(0, 10);
  const title = report.title.replace(/\s+/g, "_").replace(/[^A-Za-z0-9_-]+/g, "");
  return `${title}_${date}.${extension}`;
}

function download(blob: Blob, name: string) {
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = name;
  link.click();
  window.setTimeout(() => URL.revokeObjectURL(url), 1000);
}

function rawValue(value: string | number | undefined) {
  if (value === undefined || value === null) return "";
  return value;
}

function displayValue(value: string | number | undefined, type?: ReportValueType) {
  if (value === undefined || value === null || value === "") return "";
  if (type === "currency") return peso(value);
  if (type === "percent") return `${Number(value).toFixed(2)}%`;
  return String(value);
}

function drawPdfText(doc: jsPDF, value: string, x: number, y: number, maxWidth?: number) {
  const pesoIndex = value.indexOf("₱");
  if (pesoIndex < 0) {
    if (maxWidth === undefined) doc.text(value, x, y);
    else doc.text(value, x, y, { maxWidth });
    return;
  }

  // jsPDF's built-in Helvetica font cannot encode ₱, so draw it as P with two bars.
  const prefix = value.slice(0, pesoIndex);
  const amount = value.slice(pesoIndex + 1).trimStart();
  const symbolX = x + doc.getTextWidth(prefix);
  if (prefix) doc.text(prefix, x, y);
  const symbolWidth = doc.getTextWidth("P");
  doc.text("P", symbolX, y);

  const capHeight = doc.getFontSize() / 2.83464567;
  const extension = Math.max(0.15, capHeight * 0.05);
  const lineWidth = doc.getLineWidth();
  doc.setLineWidth(Math.max(0.12, capHeight * 0.045));
  doc.line(symbolX - extension, y - capHeight * 0.47, symbolX + symbolWidth + extension, y - capHeight * 0.47);
  doc.line(symbolX - extension, y - capHeight * 0.25, symbolX + symbolWidth + extension, y - capHeight * 0.25);
  doc.setLineWidth(lineWidth);

  const amountX = symbolX + symbolWidth + extension;
  const amountWidth = maxWidth === undefined ? undefined : Math.max(1, x + maxWidth - amountX);
  if (amountWidth === undefined) doc.text(amount, amountX, y);
  else doc.text(amount, amountX, y, { maxWidth: amountWidth });
}

function csvCell(value: string | number | undefined, type?: ReportValueType) {
  const cell = type === "currency" || type === "number" || type === "percent" ? rawValue(value) : displayValue(value, type);
  const text = String(cell);
  const safeText = typeof cell === "string" && /^[=+@\-\t\r]/.test(text) ? `'${text}` : text;
  return `"${safeText.replace(/"/g, '""')}"`;
}

function hasReportContent(report: ReportData) {
  return report.rows.length > 0 || report.summary.length > 0 || report.sections.some((item) => item.rows.length > 0);
}

export function exportReportCsv(report: ReportData) {
  if (!hasReportContent(report)) throw new Error("No data is available for the selected reporting period.");
  const rows: string[] = [];
  const addRow = (cells: Array<string | number | undefined>) => rows.push(cells.map((cell) => csvCell(cell)).join(","));
  const addTable = (title: string, columns: ReportColumn[], tableRows: Record<string, string | number>[]) => {
    addRow([]);
    addRow([title]);
    addRow(columns.map((column) => column.label));
    tableRows.forEach((row) => rows.push(columns.map((column) => csvCell(row[column.key], column.type)).join(",")));
  };

  addRow(["Business", report.business.name]);
  addRow(["Report", report.title]);
  addRow(["Report Period", report.period]);
  addRow(["Generated On", new Date(report.generatedAt).toLocaleString("en-PH", { timeZone: "Asia/Manila" })]);
  addRow(["Generated By", report.generatedBy]);
  if (report.business.address) addRow(["Address", report.business.address]);
  if (report.business.contactNumber) addRow(["Contact Number", report.business.contactNumber]);
  if (report.business.email) addRow(["Email", report.business.email]);
  addRow([]);
  addRow(["Executive Summary"]);
  addRow(["Metric", "Value"]);
  report.summary.forEach((item) => rows.push([csvCell(item.label), csvCell(item.value, item.type)].join(",")));
  addTable("Details", report.columns, report.rows);
  report.sections.forEach((section) => addTable(section.title, section.columns, section.rows));

  const csv = rows.join("\r\n");
  download(new Blob([`\uFEFF${csv}`], { type: "text/csv;charset=utf-8" }), filename(report, "csv"));
}

function applyExcelFormat(cell: ExcelJS.Cell, type?: ReportValueType) {
  if (type === "currency") cell.numFmt = '"₱" #,##0.00';
  if (type === "percent") {
    cell.value = Number(cell.value ?? 0) / 100;
    cell.numFmt = "0.00%";
  }
  if (type === "number") cell.numFmt = "#,##0";
}

function addExcelTable(worksheet: ExcelJS.Worksheet, title: string, columns: ReportColumn[], rows: Record<string, string | number>[]) {
  worksheet.addRow([]);
  worksheet.addRow([title]).font = { bold: true };
  const header = worksheet.addRow(columns.map((column) => column.label));
  header.font = { bold: true };
  header.eachCell((cell) => {
    cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFE2E8F0" } };
    cell.border = { top: { style: "thin" }, left: { style: "thin" }, bottom: { style: "thin" }, right: { style: "thin" } };
  });
  for (const row of rows) {
    const excelRow = worksheet.addRow(columns.map((column) => rawValue(row[column.key])));
    excelRow.eachCell((cell, index) => {
      applyExcelFormat(cell, columns[index - 1]?.type);
      cell.border = { top: { style: "thin" }, left: { style: "thin" }, bottom: { style: "thin" }, right: { style: "thin" } };
    });
  }
}

export async function exportReportExcel(report: ReportData) {
  if (!hasReportContent(report)) throw new Error("No data is available for the selected reporting period.");
  const workbook = new ExcelJS.Workbook();
  workbook.creator = "SmartStock";
  workbook.created = new Date();
  const worksheet = workbook.addWorksheet(report.title.slice(0, 31));
  worksheet.views = [{ state: "frozen", ySplit: 8 }];

  worksheet.addRow([report.business.name]).font = { bold: true, size: 16 };
  worksheet.addRow([report.title]).font = { bold: true, size: 14 };
  worksheet.addRow(["Report Period", report.period]);
  worksheet.addRow(["Generated On", new Date(report.generatedAt).toLocaleString("en-PH", { timeZone: "Asia/Manila" })]);
  worksheet.addRow(["Generated By", report.generatedBy]);
  worksheet.addRow([]);
  worksheet.addRow(["Summary"]).font = { bold: true };

  for (const item of report.summary) {
    const row = worksheet.addRow([item.label, rawValue(item.value)]);
    row.getCell(1).font = { bold: true };
    applyExcelFormat(row.getCell(2), item.type);
  }

  addExcelTable(worksheet, "Details", report.columns, report.rows);
  for (const item of report.sections) addExcelTable(worksheet, item.title, item.columns, item.rows);

  worksheet.columns.forEach((column) => {
    const values = column.values?.slice(1).map((value) => String(value ?? "")) ?? [];
    column.width = Math.min(Math.max(...values.map((value) => value.length), 12) + 2, 36);
  });

  const buffer = await workbook.xlsx.writeBuffer();
  download(new Blob([buffer], { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" }), filename(report, "xlsx"));
}

function drawSummary(doc: jsPDF, summary: ReportData["summary"], startY: number, margin: number, usableWidth: number) {
  if (summary.length === 0) return startY;
  const pageHeight = doc.internal.pageSize.getHeight();
  const gap = 4;
  const cardWidth = (usableWidth - gap) / 2;
  let y = startY;

  function sectionHeading(label: string) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(15, 23, 42);
    doc.text(label, margin, y);
    y += 7;
  }

  if (y + 10 > pageHeight - 17) {
    doc.addPage();
    y = margin;
  }
  sectionHeading("EXECUTIVE SUMMARY");

  for (let index = 0; index < summary.length; index += 2) {
    const cards = summary.slice(index, index + 2).map((item) => {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(7);
      const labelLines = doc.splitTextToSize(item.label, cardWidth - 8) as string[];
      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      const valueLines = doc.splitTextToSize(displayValue(item.value, item.type) || "-", cardWidth - 8) as string[];
      return { item, labelLines, valueLines, height: Math.max(15, labelLines.length * 3 + valueLines.length * 4 + 7) };
    });
    const rowHeight = Math.max(...cards.map((card) => card.height));
    if (y + rowHeight > pageHeight - 16) {
      doc.addPage();
      y = margin;
      sectionHeading("EXECUTIVE SUMMARY (CONTINUED)");
    }
    cards.forEach((card, cardIndex) => {
      const x = margin + cardIndex * (cardWidth + gap);
      doc.setFillColor(248, 250, 252);
      doc.setDrawColor(226, 232, 240);
      doc.roundedRect(x, y, cardWidth, rowHeight, 2, 2, "FD");
      doc.setFont("helvetica", "normal");
      doc.setFontSize(7);
      doc.setTextColor(71, 85, 105);
      doc.text(card.labelLines, x + 4, y + 4);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      doc.setTextColor(15, 23, 42);
      card.valueLines.forEach((line, lineIndex) => drawPdfText(doc, line, x + 4, y + 7 + card.labelLines.length * 3 + lineIndex * 4));
    });
    y += rowHeight + 3;
  }
  return y + 4;
}

function drawTable(doc: jsPDF, title: string, columns: ReportColumn[], rows: Record<string, string | number>[], startY: number, margin: number, usableWidth: number) {
  if (columns.length === 0) return startY;
  const pageHeight = doc.internal.pageSize.getHeight();
  const bottom = pageHeight - 16;
  const sampleRows = rows.slice(0, 50);
  const weights = columns.map((column) => {
    const longest = Math.max(column.label.length, ...sampleRows.map((row) => displayValue(row[column.key], column.type).length));
    return Math.min(32, Math.max(8, longest));
  });
  const totalWeight = weights.reduce((sum, weight) => sum + weight, 0);
  const widths = weights.map((weight) => usableWidth * weight / totalWeight);
  const offsets = widths.map((_, index) => widths.slice(0, index).reduce((sum, width) => sum + width, 0));
  let y = startY;

  function drawHeader() {
    const titleLines = doc.splitTextToSize(title, usableWidth) as string[];
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(15, 23, 42);
    doc.text(titleLines, margin, y);
    y += titleLines.length * 4 + 2;

    doc.setFontSize(7);
    const headerLines = columns.map((column, index) => doc.splitTextToSize(column.label, Math.max(5, widths[index] - 4)) as string[]);
    const headerHeight = Math.max(8, Math.max(...headerLines.map((lines) => lines.length)) * 3.2 + 3);
    doc.setFillColor(15, 118, 110);
    doc.rect(margin, y, usableWidth, headerHeight, "F");
    doc.setTextColor(255, 255, 255);
    columns.forEach((_, index) => doc.text(headerLines[index], margin + offsets[index] + 2, y + 3.5));
    y += headerHeight;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    doc.setTextColor(30, 41, 59);
  }

  if (y + 16 > bottom) {
    doc.addPage();
    y = margin;
  }
  drawHeader();
  if (rows.length === 0) {
    doc.setTextColor(100, 116, 139);
    doc.text("No data for this section.", margin + 2, y + 5);
    return y + 12;
  }

  rows.forEach((row, rowIndex) => {
    const cellLines = columns.map((column, index) => {
      const value = displayValue(row[column.key], column.type) || "-";
      return doc.splitTextToSize(value, Math.max(5, widths[index] - 4)) as string[];
    });
    const rowHeight = Math.max(7, Math.max(...cellLines.map((lines) => lines.length)) * 3.2 + 3);
    if (y + rowHeight > bottom) {
      doc.addPage();
      y = margin;
      drawHeader();
    }
    if (rowIndex % 2 === 1) {
      doc.setFillColor(248, 250, 252);
      doc.rect(margin, y, usableWidth, rowHeight, "F");
    }
    doc.setDrawColor(226, 232, 240);
    doc.line(margin, y + rowHeight, margin + usableWidth, y + rowHeight);
    columns.forEach((_, index) => cellLines[index].forEach((line, lineIndex) => {
      drawPdfText(doc, line, margin + offsets[index] + 2, y + 3.5 + lineIndex * 3.2, widths[index] - 4);
    }));
    y += rowHeight;
  });
  return y + 8;
}

export function exportReportPdf(report: ReportData) {
  if (!hasReportContent(report)) throw new Error("No data is available for the selected reporting period.");
  const widestTable = Math.max(report.columns.length, ...report.sections.map((section) => section.columns.length));
  const landscape = widestTable > 7;
  const doc = new jsPDF({ orientation: landscape ? "landscape" : "portrait", unit: "mm", format: "a4" });
  const margin = 12;
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const usableWidth = pageWidth - margin * 2;
  let y = 13;

  doc.setFillColor(15, 118, 110);
  doc.rect(0, 0, pageWidth, 4, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(15, 23, 42);
  doc.text(report.business.name || "SmartStock", margin, y);
  y += 6;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(71, 85, 105);
  [report.business.address, report.business.contactNumber, report.business.email].filter(Boolean).forEach((line) => {
    const wrapped = doc.splitTextToSize(line, usableWidth);
    doc.text(wrapped, margin, y);
    y += wrapped.length * 3.6;
  });
  y += 3;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.setTextColor(15, 23, 42);
  const titleLines = doc.splitTextToSize(report.title.toUpperCase(), usableWidth);
  doc.text(titleLines, margin, y);
  y += titleLines.length * 5 + 3;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(71, 85, 105);
  const metadata = [
    `Report Period: ${report.period}`,
    `Generated On: ${new Date(report.generatedAt).toLocaleString("en-PH", { timeZone: "Asia/Manila" })}`,
    `Generated By: ${report.generatedBy}`
  ];
  metadata.forEach((line) => {
    const wrapped = doc.splitTextToSize(line, usableWidth);
    doc.text(wrapped, margin, y);
    y += wrapped.length * 3.7;
  });
  y += 5;

  y = drawSummary(doc, report.summary, y, margin, usableWidth);
  y = drawTable(doc, "DETAILS", report.columns, report.rows, y, margin, usableWidth);
  report.sections.forEach((section) => {
    y = drawTable(doc, section.title, section.columns, section.rows, y, margin, usableWidth);
  });

  const pageCount = doc.getNumberOfPages();
  for (let pageNumber = 1; pageNumber <= pageCount; pageNumber += 1) {
    doc.setPage(pageNumber);
    doc.setDrawColor(203, 213, 225);
    doc.line(margin, pageHeight - 12, pageWidth - margin, pageHeight - 12);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    doc.setTextColor(100, 116, 139);
    doc.text(`${report.title} · ${report.period}`, margin, pageHeight - 7, { maxWidth: usableWidth - 25 });
    doc.text(`Page ${pageNumber} of ${pageCount}`, pageWidth - margin, pageHeight - 7, { align: "right" });
  }

  doc.save(filename(report, "pdf"));
}
